stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  service:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -P $REGISTRY_PASS
