apiVersion: v1
kind: PersistentVolume
metadata:
  name: local
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /meubanco/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          args:
            - "--ignore-db-dir=lost+found"
          imagePullPolicy: Always
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql

          volumeMounts:
            - name: local
              mountPath: /var/lib/mysql
      volumes:
        - name: local
          persistentVolumeClaim:
            claimName: local
